name: Update Downloads

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-downloads:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run download update script
        run: python update_downloads.py

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "chore: update combined downloads [skip ci]" || echo "No changes to commit"
          git push
