name: Update Downloads

on:
  # Runs daily at midnight (UTC). Feel free to adjust the cron schedule.
  schedule:
    - cron: '0 0 * * *'
  # Allows manual triggering in the GitHub Actions tab
  workflow_dispatch:

jobs:
  update-downloads:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: pip install requests
      
      - name: Run download update script
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: python update_downloads.py
      
      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add README.md
          # If README has changed, commit. Otherwise, no changes, so '|| echo ...'
          git commit -m "chore: update combined downloads [skip ci]" || echo "No changes to commit"
          git push
